name: 'MeanDao Release & Publish'
description: 'GitHub Action to release projects and publish packages'
author: '@mean-dao'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  npm_token:
    description: 'Optional. If not provided, publishing to npm will be skipped. NPM token with publish permission.'
    required: false
  access:
    description: 'Optional. Npm access flag. Default is public'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: truck
  color: red
